name = "Forge of the Ages"
author = "Keaft"
version = "0.24r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9ff05ad4e3690a7711328cea2a4fea4ade3cdb4a935ee28cc17f997a381baa2"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
