name = "Forge of the Ages"
author = "Keaft"
version = "0.26r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52e33b7b6ca8b216e85a43a78b0032c7f33e7b8f025810ce31d234c9164ab39f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
