name = "Forge of the Ages"
author = "Keaft"
version = "0.24r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f11ac9ca351347e3641e5680a533765bf826e317c09ba46196b0fed275981a98"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
