name = "Forge of the Ages"
author = "Keaft"
version = "0.24r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b59214714fa1689ae7acb9d975be535a0347f607c8f5d750d55019a1cb7c8f2"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
