name = "Forge of the Ages"
author = "Keaft"
version = "0.24r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f418331a307320f2e6b01f7e047e6ae0b0956c3290d603d767fa730f9c79782f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
