name = "Forge of the Ages"
author = "Keaft"
version = "0.24r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "584d80a4409972402e6942ffffa1bf353542aa311fd7e4cd341090c1437894a5"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
