name = "Forge of the Ages"
author = "Keaft"
version = "0.24r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b9dd888f5b6bf0501131b469b3a30e6afba79ed3c367c43381019ab2bb4ae14"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
