name = "Forge of the Ages"
author = "Keaft"
version = "0.30r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92ead9e9c63a0a03c0afa5da035b935fe8fc04ad16b314101632af9b924e5a2e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
