name = "Forge of the Ages"
author = "Keaft"
version = "0.28r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a773c6a0101ab7f0e8686cdea5d4c17c584978beec652420c15b57cc6b57cee6"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
