name = "Forge of the Ages"
author = "Keaft"
version = "0.30r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3383642db081a7e67e5380707f77bc30efa123e46870d8e1cf7ea4f1aa5f6ba"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
