name = "Forge of the Ages"
author = "Keaft"
version = "0.30r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fcd55b7c2f6296b00ac89296024d07e931be24ea92ee31ba83daff5fbe40d4a"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
