name = "Forge of the Ages"
author = "Keaft"
version = "0.24r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "901399c6927e797aa4819877be56644fe1ad254cf12f5a2a4f61d99615e9ccfb"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
