name = "Forge of the Ages"
author = "Keaft"
version = "0.29r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b041396e3111c7317131b1f2fe54d6ae6301f8ef012992fc18bddfab745c9281"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
