name = "Forge of the Ages"
author = "Keaft"
version = "0.24r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dd449c470aa6ac089757c0b800cf817c6f320390de15ce479917c6c2680b06f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
