name = "Forge of the Ages"
author = "Keaft"
version = "0.24r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a303a9b487d20776a3d316dcc3db7f1263cf32d2c649211358175cec35366cd3"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
