name = "Forge of the Ages"
author = "Keaft"
version = "0.29r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b79b3d842e4b1476c68e0aae0abcd5cb533617a424efdae96c8be3285d6057cf"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
