name = "Forge of the Ages"
author = "Keaft"
version = "0.29r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7dba3d6030eaf1961eb6ebc9ab0e8d6b8125a2d1feac69d1d470d1dabf3aae1"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
