name = "Forge of the Ages"
author = "Keaft"
version = "0.24r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "806e995777d50c3a36f700db04ffa8d998fd80dc13e9db60b2f9536e83afc51c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
