name = "Forge of the Ages"
author = "Keaft"
version = "0.30r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4315a9d6dfeea261d7a6f79eabfbf2af6cd6df071a0f4cb04d4cd6f866a6111"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
