name = "Forge of the Ages"
author = "Keaft"
version = "0.29r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34adcf0360c2953a05a397226bcb45b8095209a7378995bfc80d79ca1b4d88ed"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
