name = "Forge of the Ages"
author = "Keaft"
version = "0.24r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "743a07859631e8d1810ab41d72d02ea80f7a7a2e30ab86d43aa05fa7a0705e70"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
