name = "Forge of the Ages"
author = "Keaft"
version = "0.28r"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05b2bb2793913f5c635fbc5604030494c4b30b462a3e9f87b11f77c005bf2d17"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
